DATA_PATH: "dataset"
CAT_API_URL: "https://api.thecatapi.com/v1/images/search?mime_types=jpg"
DOG_API_URL: "https://api.thedogapi.com/v1/images/search?mime_types=jpg"
NUM_IMAGES: 1000
IMAGE_SIZE: 128
BATCH_SIZE: 32
EPOCHS: 50
LEARNING_RATE: 0.00001
DROPOUT_PROB: 0.4
NUM_CLASSES: 2
SEED: 42
DEVICE: "cuda"
TRANSFER_BACKBONE: "resnet18"
