DATA_PATH: "ready_dataset_2.csv"
MAX_SEQ_LEN: 100
VOCAB_SIZE: 10000
EMBEDDING_DIM: 128
HIDDEN_DIM: 128
NUM_CLASSES: 2
BATCH_SIZE: 32
EPOCHS: 100
LEARNING_RATE: 0.00001
DROPOUT_PROB: 0.3
DEVICE: "cuda"
